/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

float *
calculadora_1_svc(datos *argp, struct svc_req *rqstp)
{
	static float  result;

	char op = argp->opcion;
	switch(op){
		case '+': result= argp->dato1 + argp->dato2;
		break;
		case '-': result= argp->dato1 - argp->dato2;
		break;
		case '*': result= argp->dato1 * argp->dato2;
		break;
		case '/': result= argp->dato1 / argp->dato2;
		break;
	}
	return &result;
}
