/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadora_prg_1(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	datos  calculadora_1_arg;
	scanf("%c",&calculadora_1_arg.opcion);
	scanf("%f",&calculadora_1_arg.dato1);
	scanf("%f",&calculadora_1_arg.dato2);
#ifndef	DEBUG
	clnt = clnt_create (host, calculadora_PRG, calculadora_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = calculadora_1(&calculadora_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("el resultado es :%f",*result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calculadora_prg_1 (host);
exit (0);
}
